### ISSUE TITLE
[Team 1] [0.5xpt] Add unit tests for all implemented methods.

### ISSUE THREAD

**Issue by sambeck87** [sambeck87/ruby_group_capstone#12]
- Should override the method from the parent class.
- Should return true if parent's method returns true AND if last_played_at is older than 2 years.
- Otherwise, it should return false.

**Comment by Juank628** [comment]
- should override the method from the parent class
- should return true if parent's method returns true OR if cover_state equals to "bad"
- otherwise, it should return false
